[package]
name = "graphite"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "graphite_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
graphite-core = { path = "../../../crates/graphite-core" }
graphite-drivers = { path = "../../../crates/graphite-drivers" }
graphite-appdb = { path = "../../../crates/graphite-appdb" }
graphite-ssh = { path = "../../../crates/graphite-ssh" }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
